### ISSUE TITLE
Shorteners not working in Win10 Pro x64

### ISSUE THREAD

**Issue by jakesgit** [raguay/favorites#11]
Hi, firstly thanks for the neat plugin.

Everything works as intended for the mostpart but I have defined several shorteners which do not seem to work (or I have misunderstood what they are supposed to be!)

For example, if I defined a shortener named `123` for dir `C:\Users`, then press `Ctrl + P` and enter `123` I don't see the directory listed.

If I can provide any additional info that may be of use please let me know!

Cheers

**Comment by raguay** [comment]
Hi, the directory shortener is for creating favorites based on the
shortener. For example, my two macs have different paths to the Dropbox
directory. So, I create a shortener to the Dropbox directory on both
systems using the same name. Then, I create favorites inside the Dropbox
directory. The favorites can be shared between the two systems without
changing anything since their path is based on the shortener.

Since you can create a favorite with any name, that is what you would use
to make your alias. But, favorites can't be used inside the `Ctrl + P`
since it is a plugin and not a built in function. `Ctrl + P` will only work
with full path names and not shorten names.
