### ISSUE TITLE
Add a pair of directories at once

### ISSUE THREAD

**Issue by ababak** [raguay/favorites#12]
Often there's a need to copy files between pre-defined locations. I can have about 5-10 of such sets. It would be very convenient to be able to quickly set them in pairs.

**Comment by raguay** [comment]
Just added it as directory pairs. There are now three new commands: Set Favorite Directory Pair, Remove Favorite Directory Pair, and Go To Favorite Directory Pair. Give it a try and let me know if this is what you need.

**Comment by raguay** [comment]
BTW: To install the new version, you have to remove the plugin and re-install it.

**Comment by ababak** [comment]
Thank you, Richard. Works like a charm!
Maybe, a keyboard shortcut for "Go to favorite pair" will be a good idea.

**Comment by raguay** [comment]
goto `~/Library/Application Support/fman/Plugins/User/Settings/Key Bindings.json` and add the one you want. Take the name of the command and make it camel case. Therefore, 'Go to favorite pair' becomes 'goToFavoritePair' for the keybinding. That way you can make it to any key sequence you want instead of using what I like.
