### ISSUE TITLE
Newest Release is Broken in Current fman Version (0.8.4)

### ISSUE THREAD

**Issue by Akamaozu** [raguay/favorites#5]
Seems like fman's plugin install uses this plugin's latest release tag (https://github.com/raguay/favorites/releases/tag/1.6.1), which doesn't work with the current fman release (0.8.4).

Need to create a new release tag.

Ps.
Not sure how plugins resolve which version of fman they can work with, but it seems necessary to find some way to resolve this.

cc: @mherrmann

**Comment by mherrmann** [comment]
If a release is available for a plugin, then fman installs the release rather than the latest development version. This lets plugin developers make changes, and only "publish" a new version once they're ready.

The simple fix for this problem should be to [Draft a new release](https://github.com/raguay/favorites/releases/new).

**Comment by Akamaozu** [comment]
What about in case of incompatible versions of fman and plugin release?

For example, if I have an older version of fman and try installing a plugin
whose latest release uses the new file url, will the installer know the
latest plugin release won't work for me?

**Comment by mherrmann** [comment]
No, I'm afraid it won't. fman is still in 0.x.x stage so I purposely update the API to reflect new learnings. Once 1.0.0 is out, there will be an "API version 1" which will guaranteed to be stable. To use "old versions" of a plugin, you need to download and install them manually.

**Comment by Akamaozu** [comment]
Good to know. Thanks for the info :)

**Comment by mherrmann** [comment]
My pleasure :-)
