### ISSUE TITLE
Go to favorite shortcut doesn't work

### ISSUE THREAD

**Issue by kaniawave** [raguay/favorites#9]
Hello
I can set up the favorite folders and reach them by `CTRL+SHIFT+P` and then `Go to favorite`. The custom shortcut `CTRL+0` doesn't work. Reloading plugins have no effect.

fman 1.5.0

Greets

**Comment by raguay** [comment]
If you look in the `Key Bindings.json` file of the plugin folder `~/Library/Application Support/fman/Plugins/Third-party/favorites/`, you can see all the keybindings for the plugin. Don't change that file as it is changed if you update the favorites plugin. Add the appropriate line to your `~/Library/Application Support/fman/Plugins/User/Settings/Key Bindings.json` file. You can change all the fman keybindings in this file and it will be preserved between fman updates and plugin updates.

BTW: You must have another program mapping the `<ctrl>+0` keybinding. That is the only way that it would not work. Honestly, I use the command pallet more than the keybindings.

**Comment by generic-user** [comment]
I seem to have the same issue, I think it has something to do with the keyboard layout (`azerty-be`) not being the same as was used by the programmer (`qwerty-en`). I also think the problem could be in the _QT-shortcut-keys_ implementation rather than in this plugin implementation.

## Hijacking?
Nothing is hijacking the `CTRL+0` here. 
It just does not seem to work. 

> I remember having the same issue with early installments of ‘SublimeText’ editor.

## Reopen?
Anyway I do not think you should dismiss this issue so easily as it breaks some core functions of the plugin on certain environments. It could be the issue should be reported on another level? A _fman_-issue?

## How to test the problem?
U can test this in windows quite easy, just switch the keyboard layout from English(UK) `qwerty` to Belgium `azerty`. Then reload the plugins, and notice the unwanted behavior.

## Uncomfortable
Anyway, this is just my two cents. It seems like an issue that is quite uncomfortable, especially for the not so tech-savy under the new users.

## Thanks
Thanks for the plugin! And I hope you keep up the good work! 👍

**Comment by raguay** [comment]
Hi,

That is an issue with QT. QT handles the keyboard inputs and translate them
to the program using the framework. Fman and my plugin can't change that
behaviour (well, execpt for using some other framework than QT). I've seen
similar issues in other QT programs. Sorry.

**Comment by generic-user** [comment]
Thanks for the response, that’s what I suspected.
Maybe add a warning in the read me file of your plugin explaining the problem, linking to this issue.

Would safe other users some time looking into the issue them self.
